# Generated by Django 5.2 on 2026-05-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salidaproducto',
            name='motivo',
            field=models.CharField(max_length=255),
        ),
    ]
