# Generated by Django 5.2 on 2026-05-18 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0002_alter_salidaproducto_motivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='entradaproducto',
            options={'verbose_name': 'EntradaProducto', 'verbose_name_plural': 'EntradaProductos'},
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'verbose_name': 'OrdenCompra', 'verbose_name_plural': 'OrdenCompras'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='salidaproducto',
            options={'verbose_name': 'SalidaProducto', 'verbose_name_plural': 'SalidaProductos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
