# Generated by Django 5.2 on 2026-05-19 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0003_alter_categoria_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock_minimo',
        ),
    ]
